version: 0.0
os: ubuntu

files: 
  - source: target/AWSLambdaDemoApplication-1.0.jar
    destination: /home/ubuntu

permissions: 
  - object: / 
    pattern: "**" 
    owner: ubuntu
    group: ubuntu
