version: 0.0
os: linux
#os: ubuntu

files: 
  - source: /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/target/AWSLambdaDemoApplication-1.0-SNAPSHOT.jar
    destination: /

permissions: 
  - object: / 
    pattern: "**" 
    owner: root
    group: root
