version: 0.0
os: linux
files:
  - source: /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/*
    destination: /tmp/java
hooks:
  # ApplicationStop:
  #   - location: deregister_from_elb.sh
  # ApplicationStart:
  ValidateService:
    - location: aws-s3.sh