version: 0.2

phases:
  install:
    #runtime-versions:
      #java: corretto11
      #java: openjdk8
    commands:  
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - java -version
      - apt-get install -y maven
      - mvn -version
      - echo "testing applications for maven"
      - apt-get install zip
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo "Build started on `date`"
      - mvn install
      - pwd
      - ls -al /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/target/
  post_build:
    commands:
      - echo "Build completed on `date`"
      - cp -r /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/target/ /tmp
      - cd /tmp/target && zip -X -r Spring-Serverless-Demo-1.zip AWSLambdaDemoApplication-1.0-SNAPSHOT.jar
#       - zip -X -r /tmp/Spring-Serverless-Demo.zip /tmp/Spring-*
      - ls /tmp/target
      - aws lambda update-function-code --function-name spring-serverless-demo --zip-file fileb:///tmp/target/Spring-Serverless-Demo-1.zip
#       - zip -X -r Spring-Serverless-Demo.zip /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/*
#       - aws lambda update-function-code --function-name spring-serverless-demo --zip-file fileb://Spring-Serverless-Demo.zip
#       - aws lambda update-function-code --function-name spring-serverless-demo --zip-file fileb:///codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo.zip
artifacts:
  files:
    - appspec.yml
    - /tmp/target/Spring-Serverless-Demo-1.zip
#     - /codebuild/output/*/src/github.com/sumit-orient/Spring-Serverless-Demo/*
  discard-paths: yes
