version: 0.2

phases:
  install:
    runtime-versions:
      #java: corretto11
      java: openjdk8
    # runtime-versions:
    #   java: corretto11
  build:
    commands:
      - mvn package
      - mvn install
      - sam package 
        --template-file sam-template.yml 
        --s3-bucket aws-lambda-demo-application-new-s3-bucket 
        --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml