version: 0.2

phases:
  install:
    #runtime-versions:
      #java: corretto11
    commands:  
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - java -version
      - apt-get install -y maven
      - mvn -version
      - echo "testing applications for maven"
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo "Build started on `date`"
      - mvn install
      - pwd
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - appspec.yml
    - ./target/AWSLambdaDemoApplication-1.0.jar
  discard-paths: yes
